### ISSUE TITLE
Process 'MobSync.exe' always suspended

### ISSUE THREAD

**Issue by WanderingCoder-Omen** [cribdragg3r/Alaris#3]
Hi first of all great work. The idea of using direct calls and encrypted shellcode along with process hollowing and PPID spoofing is really cool. However I am facing a few issues. I compiled a fresh copy of the solution on a VM and generated the two exes. However cant get the loader to connect to the listener on localhost. The mobsync.exe process stays suspended.
I am also getting a couple of warnings. I've attached a couple of screenshots. Can you identify what I'm doing wrong?
![Capture](https://user-images.githubusercontent.com/60088552/103879852-3aad9f80-508d-11eb-8d28-46a904b652c8.PNG)
No connects :(

![2](https://user-images.githubusercontent.com/60088552/103879887-45683480-508d-11eb-9dcd-ae2194a78b55.PNG)
The warnings

![3](https://user-images.githubusercontent.com/60088552/103879913-4d27d900-508d-11eb-96fb-a72d654c443a.PNG)
OS and machine info

**Comment by cribdragg3r** [comment]
Hey,

I've pushed out a new version that may help with this. I think the issue may have been overwriting the shellcode prematurely and I've since added a 10 second buffer between hollow and and overwrite. Currently, I do not have any "Default" shellcode that will run like I did in the last revision. Could you generate some x64 shellcode (CS, Metasploit, etc.) and try?
